// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    id,
    username,
    username_normalized,
    display_name,
    disabled,
    mfa_required,
    locked_until,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, username, username_normalized, display_name, disabled, mfa_required, locked_until, metadata, created_at, updated_at
`

type CreateAccountParams struct {
	ID                 pgtype.UUID        `json:"id"`
	Username           string             `json:"username"`
	UsernameNormalized string             `json:"username_normalized"`
	DisplayName        string             `json:"display_name"`
	Disabled           bool               `json:"disabled"`
	MfaRequired        bool               `json:"mfa_required"`
	LockedUntil        pgtype.Timestamptz `json:"locked_until"`
	Metadata           []byte             `json:"metadata"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.Username,
		arg.UsernameNormalized,
		arg.DisplayName,
		arg.Disabled,
		arg.MfaRequired,
		arg.LockedUntil,
		arg.Metadata,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameNormalized,
		&i.DisplayName,
		&i.Disabled,
		&i.MfaRequired,
		&i.LockedUntil,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEmail = `-- name: CreateEmail :one
INSERT INTO emails (
    id,
    account_id,
    address,
    address_normalized,
    verified,
    is_primary,
    verified_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, account_id, address, address_normalized, verified, is_primary, verified_at, created_at, updated_at
`

type CreateEmailParams struct {
	ID                pgtype.UUID        `json:"id"`
	AccountID         pgtype.UUID        `json:"account_id"`
	Address           string             `json:"address"`
	AddressNormalized string             `json:"address_normalized"`
	Verified          bool               `json:"verified"`
	IsPrimary         bool               `json:"is_primary"`
	VerifiedAt        pgtype.Timestamptz `json:"verified_at"`
}

func (q *Queries) CreateEmail(ctx context.Context, arg CreateEmailParams) (Email, error) {
	row := q.db.QueryRow(ctx, createEmail,
		arg.ID,
		arg.AccountID,
		arg.Address,
		arg.AddressNormalized,
		arg.Verified,
		arg.IsPrimary,
		arg.VerifiedAt,
	)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Address,
		&i.AddressNormalized,
		&i.Verified,
		&i.IsPrimary,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT a.id, a.username, a.username_normalized, a.display_name, a.disabled, a.mfa_required, a.locked_until, a.metadata, a.created_at, a.updated_at
FROM accounts AS a
JOIN emails AS e ON e.account_id = a.id
WHERE e.address_normalized = $1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, addressNormalized string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, addressNormalized)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameNormalized,
		&i.DisplayName,
		&i.Disabled,
		&i.MfaRequired,
		&i.LockedUntil,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, username, username_normalized, display_name, disabled, mfa_required, locked_until, metadata, created_at, updated_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameNormalized,
		&i.DisplayName,
		&i.Disabled,
		&i.MfaRequired,
		&i.LockedUntil,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, username, username_normalized, display_name, disabled, mfa_required, locked_until, metadata, created_at, updated_at
FROM accounts
WHERE username_normalized = $1
`

func (q *Queries) GetAccountByUsername(ctx context.Context, usernameNormalized string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUsername, usernameNormalized)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameNormalized,
		&i.DisplayName,
		&i.Disabled,
		&i.MfaRequired,
		&i.LockedUntil,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmailsByAccount = `-- name: ListEmailsByAccount :many
SELECT id, account_id, address, address_normalized, verified, is_primary, verified_at, created_at, updated_at
FROM emails
WHERE account_id = $1
ORDER BY is_primary DESC, created_at ASC
`

func (q *Queries) ListEmailsByAccount(ctx context.Context, accountID pgtype.UUID) ([]Email, error) {
	rows, err := q.db.Query(ctx, listEmailsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Email{}
	for rows.Next() {
		var i Email
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Address,
			&i.AddressNormalized,
			&i.Verified,
			&i.IsPrimary,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountLockout = `-- name: UpdateAccountLockout :one
UPDATE accounts
SET locked_until = $1
WHERE id = $2
RETURNING id, username, username_normalized, display_name, disabled, mfa_required, locked_until, metadata, created_at, updated_at
`

type UpdateAccountLockoutParams struct {
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
	ID          pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateAccountLockout(ctx context.Context, arg UpdateAccountLockoutParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountLockout, arg.LockedUntil, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameNormalized,
		&i.DisplayName,
		&i.Disabled,
		&i.MfaRequired,
		&i.LockedUntil,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
