// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendAuditEvent = `-- name: AppendAuditEvent :one
INSERT INTO audit_events (
    id,
    event_type,
    account_id,
    credential_id,
    session_id,
    client_id,
    organization_id,
    request_id,
    ip,
    user_agent,
    occurred_at,
    attributes
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING id, event_type, account_id, credential_id, session_id, client_id, organization_id, request_id, ip, user_agent, occurred_at, attributes, created_at
`

type AppendAuditEventParams struct {
	ID             pgtype.UUID        `json:"id"`
	EventType      string             `json:"event_type"`
	AccountID      pgtype.UUID        `json:"account_id"`
	CredentialID   pgtype.UUID        `json:"credential_id"`
	SessionID      pgtype.UUID        `json:"session_id"`
	ClientID       pgtype.UUID        `json:"client_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	RequestID      string             `json:"request_id"`
	Ip             *netip.Addr        `json:"ip"`
	UserAgent      string             `json:"user_agent"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	Attributes     []byte             `json:"attributes"`
}

func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, appendAuditEvent,
		arg.ID,
		arg.EventType,
		arg.AccountID,
		arg.CredentialID,
		arg.SessionID,
		arg.ClientID,
		arg.OrganizationID,
		arg.RequestID,
		arg.Ip,
		arg.UserAgent,
		arg.OccurredAt,
		arg.Attributes,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.AccountID,
		&i.CredentialID,
		&i.SessionID,
		&i.ClientID,
		&i.OrganizationID,
		&i.RequestID,
		&i.Ip,
		&i.UserAgent,
		&i.OccurredAt,
		&i.Attributes,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentLoginAuditEvents = `-- name: ListRecentLoginAuditEvents :many
SELECT id, event_type, account_id, credential_id, session_id, client_id, organization_id, request_id, ip, user_agent, occurred_at, attributes, created_at
FROM audit_events
WHERE account_id = $1
  AND event_type = ANY($2::text[])
ORDER BY occurred_at DESC
LIMIT $3
`

type ListRecentLoginAuditEventsParams struct {
	AccountID  pgtype.UUID `json:"account_id"`
	EventTypes []string    `json:"event_types"`
	RowLimit   int32       `json:"row_limit"`
}

func (q *Queries) ListRecentLoginAuditEvents(ctx context.Context, arg ListRecentLoginAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listRecentLoginAuditEvents, arg.AccountID, arg.EventTypes, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AccountID,
			&i.CredentialID,
			&i.SessionID,
			&i.ClientID,
			&i.OrganizationID,
			&i.RequestID,
			&i.Ip,
			&i.UserAgent,
			&i.OccurredAt,
			&i.Attributes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
