// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: challenges.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAuthChallenge = `-- name: ConsumeAuthChallenge :one
UPDATE auth_challenges
SET consumed_at = $1
WHERE id = $2
  AND consumed_at IS NULL
  AND expires_at > $1
RETURNING id, purpose, account_id, credential_id, provider, session_binding, request_id, payload, expires_at, consumed_at, created_at
`

type ConsumeAuthChallengeParams struct {
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	ID         string             `json:"id"`
}

func (q *Queries) ConsumeAuthChallenge(ctx context.Context, arg ConsumeAuthChallengeParams) (AuthChallenge, error) {
	row := q.db.QueryRow(ctx, consumeAuthChallenge, arg.ConsumedAt, arg.ID)
	var i AuthChallenge
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.AccountID,
		&i.CredentialID,
		&i.Provider,
		&i.SessionBinding,
		&i.RequestID,
		&i.Payload,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const consumeOIDCPendingState = `-- name: ConsumeOIDCPendingState :one
UPDATE oidc_pending_states
SET consumed_at = $1
WHERE provider = $2
  AND state_hash = $3
  AND consumed_at IS NULL
  AND expires_at > $1
RETURNING id, provider, session_binding, state_hash, nonce_hash, pkce_verifier_ciphertext, redirect_uri, expires_at, consumed_at, created_at
`

type ConsumeOIDCPendingStateParams struct {
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	Provider   string             `json:"provider"`
	StateHash  []byte             `json:"state_hash"`
}

func (q *Queries) ConsumeOIDCPendingState(ctx context.Context, arg ConsumeOIDCPendingStateParams) (OidcPendingState, error) {
	row := q.db.QueryRow(ctx, consumeOIDCPendingState, arg.ConsumedAt, arg.Provider, arg.StateHash)
	var i OidcPendingState
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.SessionBinding,
		&i.StateHash,
		&i.NonceHash,
		&i.PkceVerifierCiphertext,
		&i.RedirectUri,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAuthChallenge = `-- name: CreateAuthChallenge :one
INSERT INTO auth_challenges (
    id,
    purpose,
    account_id,
    credential_id,
    provider,
    session_binding,
    request_id,
    payload,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, purpose, account_id, credential_id, provider, session_binding, request_id, payload, expires_at, consumed_at, created_at
`

type CreateAuthChallengeParams struct {
	ID             string             `json:"id"`
	Purpose        string             `json:"purpose"`
	AccountID      pgtype.UUID        `json:"account_id"`
	CredentialID   pgtype.UUID        `json:"credential_id"`
	Provider       *string            `json:"provider"`
	SessionBinding string             `json:"session_binding"`
	RequestID      string             `json:"request_id"`
	Payload        []byte             `json:"payload"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuthChallenge(ctx context.Context, arg CreateAuthChallengeParams) (AuthChallenge, error) {
	row := q.db.QueryRow(ctx, createAuthChallenge,
		arg.ID,
		arg.Purpose,
		arg.AccountID,
		arg.CredentialID,
		arg.Provider,
		arg.SessionBinding,
		arg.RequestID,
		arg.Payload,
		arg.ExpiresAt,
	)
	var i AuthChallenge
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.AccountID,
		&i.CredentialID,
		&i.Provider,
		&i.SessionBinding,
		&i.RequestID,
		&i.Payload,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOIDCPendingState = `-- name: CreateOIDCPendingState :one
INSERT INTO oidc_pending_states (
    id,
    provider,
    session_binding,
    state_hash,
    nonce_hash,
    pkce_verifier_ciphertext,
    redirect_uri,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, provider, session_binding, state_hash, nonce_hash, pkce_verifier_ciphertext, redirect_uri, expires_at, consumed_at, created_at
`

type CreateOIDCPendingStateParams struct {
	ID                     string             `json:"id"`
	Provider               string             `json:"provider"`
	SessionBinding         string             `json:"session_binding"`
	StateHash              []byte             `json:"state_hash"`
	NonceHash              []byte             `json:"nonce_hash"`
	PkceVerifierCiphertext []byte             `json:"pkce_verifier_ciphertext"`
	RedirectUri            string             `json:"redirect_uri"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOIDCPendingState(ctx context.Context, arg CreateOIDCPendingStateParams) (OidcPendingState, error) {
	row := q.db.QueryRow(ctx, createOIDCPendingState,
		arg.ID,
		arg.Provider,
		arg.SessionBinding,
		arg.StateHash,
		arg.NonceHash,
		arg.PkceVerifierCiphertext,
		arg.RedirectUri,
		arg.ExpiresAt,
	)
	var i OidcPendingState
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.SessionBinding,
		&i.StateHash,
		&i.NonceHash,
		&i.PkceVerifierCiphertext,
		&i.RedirectUri,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAuthChallenge = `-- name: DeleteAuthChallenge :execrows
DELETE FROM auth_challenges
WHERE id = $1
`

func (q *Queries) DeleteAuthChallenge(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuthChallenge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredAuthChallenges = `-- name: DeleteExpiredAuthChallenges :execrows
DELETE FROM auth_challenges
WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredAuthChallenges(ctx context.Context, expiredAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthChallenges, expiredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredOIDCPendingStates = `-- name: DeleteExpiredOIDCPendingStates :execrows
DELETE FROM oidc_pending_states
WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredOIDCPendingStates(ctx context.Context, expiredAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOIDCPendingStates, expiredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuthChallenge = `-- name: GetAuthChallenge :one
SELECT id, purpose, account_id, credential_id, provider, session_binding, request_id, payload, expires_at, consumed_at, created_at
FROM auth_challenges
WHERE id = $1
`

func (q *Queries) GetAuthChallenge(ctx context.Context, id string) (AuthChallenge, error) {
	row := q.db.QueryRow(ctx, getAuthChallenge, id)
	var i AuthChallenge
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.AccountID,
		&i.CredentialID,
		&i.Provider,
		&i.SessionBinding,
		&i.RequestID,
		&i.Payload,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listExpiredAuthChallenges = `-- name: ListExpiredAuthChallenges :many
SELECT id, purpose, account_id, credential_id, provider, session_binding, request_id, payload, expires_at, consumed_at, created_at
FROM auth_challenges
WHERE expires_at <= $1
ORDER BY expires_at ASC
LIMIT $2
`

type ListExpiredAuthChallengesParams struct {
	ExpiredAt pgtype.Timestamptz `json:"expired_at"`
	RowLimit  int32              `json:"row_limit"`
}

func (q *Queries) ListExpiredAuthChallenges(ctx context.Context, arg ListExpiredAuthChallengesParams) ([]AuthChallenge, error) {
	rows, err := q.db.Query(ctx, listExpiredAuthChallenges, arg.ExpiredAt, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthChallenge{}
	for rows.Next() {
		var i AuthChallenge
		if err := rows.Scan(
			&i.ID,
			&i.Purpose,
			&i.AccountID,
			&i.CredentialID,
			&i.Provider,
			&i.SessionBinding,
			&i.RequestID,
			&i.Payload,
			&i.ExpiresAt,
			&i.ConsumedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
