// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (
    id,
    account_id,
    kind,
    provider,
    external_subject,
    display_name,
    verified
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, account_id, kind, provider, external_subject, display_name, verified, created_at, updated_at, last_used_at, revoked_at
`

type CreateCredentialParams struct {
	ID              pgtype.UUID `json:"id"`
	AccountID       pgtype.UUID `json:"account_id"`
	Kind            string      `json:"kind"`
	Provider        *string     `json:"provider"`
	ExternalSubject *string     `json:"external_subject"`
	DisplayName     string      `json:"display_name"`
	Verified        bool        `json:"verified"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.ID,
		arg.AccountID,
		arg.Kind,
		arg.Provider,
		arg.ExternalSubject,
		arg.DisplayName,
		arg.Verified,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.Provider,
		&i.ExternalSubject,
		&i.DisplayName,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getCredentialByAccountKindProvider = `-- name: GetCredentialByAccountKindProvider :one
SELECT id, account_id, kind, provider, external_subject, display_name, verified, created_at, updated_at, last_used_at, revoked_at
FROM credentials
WHERE account_id = $1
  AND kind = $2
  AND provider IS NOT DISTINCT FROM $3
  AND revoked_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetCredentialByAccountKindProviderParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Kind      string      `json:"kind"`
	Provider  *string     `json:"provider"`
}

func (q *Queries) GetCredentialByAccountKindProvider(ctx context.Context, arg GetCredentialByAccountKindProviderParams) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredentialByAccountKindProvider, arg.AccountID, arg.Kind, arg.Provider)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.Provider,
		&i.ExternalSubject,
		&i.DisplayName,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getCredentialByID = `-- name: GetCredentialByID :one
SELECT id, account_id, kind, provider, external_subject, display_name, verified, created_at, updated_at, last_used_at, revoked_at
FROM credentials
WHERE id = $1
`

func (q *Queries) GetCredentialByID(ctx context.Context, id pgtype.UUID) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredentialByID, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.Provider,
		&i.ExternalSubject,
		&i.DisplayName,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getCredentialByProviderSubject = `-- name: GetCredentialByProviderSubject :one
SELECT id, account_id, kind, provider, external_subject, display_name, verified, created_at, updated_at, last_used_at, revoked_at
FROM credentials
WHERE kind = $1
  AND provider = $2
  AND external_subject = $3
  AND revoked_at IS NULL
`

type GetCredentialByProviderSubjectParams struct {
	Kind            string  `json:"kind"`
	Provider        *string `json:"provider"`
	ExternalSubject *string `json:"external_subject"`
}

func (q *Queries) GetCredentialByProviderSubject(ctx context.Context, arg GetCredentialByProviderSubjectParams) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredentialByProviderSubject, arg.Kind, arg.Provider, arg.ExternalSubject)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.Provider,
		&i.ExternalSubject,
		&i.DisplayName,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getCredentialPayload = `-- name: GetCredentialPayload :one
SELECT credential_id, algorithm, key_ref, nonce, ciphertext, aad, version, created_at, updated_at
FROM credential_payloads
WHERE credential_id = $1
`

func (q *Queries) GetCredentialPayload(ctx context.Context, credentialID pgtype.UUID) (CredentialPayload, error) {
	row := q.db.QueryRow(ctx, getCredentialPayload, credentialID)
	var i CredentialPayload
	err := row.Scan(
		&i.CredentialID,
		&i.Algorithm,
		&i.KeyRef,
		&i.Nonce,
		&i.Ciphertext,
		&i.Aad,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCredentialsByAccount = `-- name: ListCredentialsByAccount :many
SELECT id, account_id, kind, provider, external_subject, display_name, verified, created_at, updated_at, last_used_at, revoked_at
FROM credentials
WHERE account_id = $1
  AND revoked_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListCredentialsByAccount(ctx context.Context, accountID pgtype.UUID) ([]Credential, error) {
	rows, err := q.db.Query(ctx, listCredentialsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Credential{}
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Kind,
			&i.Provider,
			&i.ExternalSubject,
			&i.DisplayName,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialsByAccountAndKind = `-- name: ListCredentialsByAccountAndKind :many
SELECT id, account_id, kind, provider, external_subject, display_name, verified, created_at, updated_at, last_used_at, revoked_at
FROM credentials
WHERE account_id = $1
  AND kind = $2
  AND revoked_at IS NULL
ORDER BY created_at ASC
`

type ListCredentialsByAccountAndKindParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Kind      string      `json:"kind"`
}

func (q *Queries) ListCredentialsByAccountAndKind(ctx context.Context, arg ListCredentialsByAccountAndKindParams) ([]Credential, error) {
	rows, err := q.db.Query(ctx, listCredentialsByAccountAndKind, arg.AccountID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Credential{}
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Kind,
			&i.Provider,
			&i.ExternalSubject,
			&i.DisplayName,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCredential = `-- name: RevokeCredential :one
UPDATE credentials
SET revoked_at = $1
WHERE id = $2
  AND revoked_at IS NULL
RETURNING id, account_id, kind, provider, external_subject, display_name, verified, created_at, updated_at, last_used_at, revoked_at
`

type RevokeCredentialParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) RevokeCredential(ctx context.Context, arg RevokeCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, revokeCredential, arg.RevokedAt, arg.ID)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.Provider,
		&i.ExternalSubject,
		&i.DisplayName,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateCredentialLastUsed = `-- name: UpdateCredentialLastUsed :one
UPDATE credentials
SET last_used_at = $1
WHERE id = $2
RETURNING id, account_id, kind, provider, external_subject, display_name, verified, created_at, updated_at, last_used_at, revoked_at
`

type UpdateCredentialLastUsedParams struct {
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ID         pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateCredentialLastUsed(ctx context.Context, arg UpdateCredentialLastUsedParams) (Credential, error) {
	row := q.db.QueryRow(ctx, updateCredentialLastUsed, arg.LastUsedAt, arg.ID)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.Provider,
		&i.ExternalSubject,
		&i.DisplayName,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const upsertCredentialPayload = `-- name: UpsertCredentialPayload :one
INSERT INTO credential_payloads (
    credential_id,
    algorithm,
    key_ref,
    nonce,
    ciphertext,
    aad,
    version
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (credential_id) DO UPDATE
SET algorithm = EXCLUDED.algorithm,
    key_ref = EXCLUDED.key_ref,
    nonce = EXCLUDED.nonce,
    ciphertext = EXCLUDED.ciphertext,
    aad = EXCLUDED.aad,
    version = EXCLUDED.version
RETURNING credential_id, algorithm, key_ref, nonce, ciphertext, aad, version, created_at, updated_at
`

type UpsertCredentialPayloadParams struct {
	CredentialID pgtype.UUID `json:"credential_id"`
	Algorithm    string      `json:"algorithm"`
	KeyRef       string      `json:"key_ref"`
	Nonce        []byte      `json:"nonce"`
	Ciphertext   []byte      `json:"ciphertext"`
	Aad          []byte      `json:"aad"`
	Version      int32       `json:"version"`
}

func (q *Queries) UpsertCredentialPayload(ctx context.Context, arg UpsertCredentialPayloadParams) (CredentialPayload, error) {
	row := q.db.QueryRow(ctx, upsertCredentialPayload,
		arg.CredentialID,
		arg.Algorithm,
		arg.KeyRef,
		arg.Nonce,
		arg.Ciphertext,
		arg.Aad,
		arg.Version,
	)
	var i CredentialPayload
	err := row.Scan(
		&i.CredentialID,
		&i.Algorithm,
		&i.KeyRef,
		&i.Nonce,
		&i.Ciphertext,
		&i.Aad,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
