// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_attempts.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearExpiredLoginAttemptLocks = `-- name: ClearExpiredLoginAttemptLocks :execrows
UPDATE login_attempts
SET locked_until = NULL
WHERE locked_until IS NOT NULL
  AND locked_until <= $1
`

func (q *Queries) ClearExpiredLoginAttemptLocks(ctx context.Context, expiredAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, clearExpiredLoginAttemptLocks, expiredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLoginAttempt = `-- name: GetLoginAttempt :one
SELECT id, endpoint, subject_type, subject_hash, account_id, username_normalized, ip, failed_count, locked_until, last_failed_at, last_success_at, created_at, updated_at
FROM login_attempts
WHERE endpoint = $1
  AND subject_type = $2
  AND subject_hash = $3
`

type GetLoginAttemptParams struct {
	Endpoint    string `json:"endpoint"`
	SubjectType string `json:"subject_type"`
	SubjectHash string `json:"subject_hash"`
}

func (q *Queries) GetLoginAttempt(ctx context.Context, arg GetLoginAttemptParams) (LoginAttempt, error) {
	row := q.db.QueryRow(ctx, getLoginAttempt, arg.Endpoint, arg.SubjectType, arg.SubjectHash)
	var i LoginAttempt
	err := row.Scan(
		&i.ID,
		&i.Endpoint,
		&i.SubjectType,
		&i.SubjectHash,
		&i.AccountID,
		&i.UsernameNormalized,
		&i.Ip,
		&i.FailedCount,
		&i.LockedUntil,
		&i.LastFailedAt,
		&i.LastSuccessAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockLoginAttemptUntil = `-- name: LockLoginAttemptUntil :one
UPDATE login_attempts
SET locked_until = $1
WHERE endpoint = $2
  AND subject_type = $3
  AND subject_hash = $4
RETURNING id, endpoint, subject_type, subject_hash, account_id, username_normalized, ip, failed_count, locked_until, last_failed_at, last_success_at, created_at, updated_at
`

type LockLoginAttemptUntilParams struct {
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
	Endpoint    string             `json:"endpoint"`
	SubjectType string             `json:"subject_type"`
	SubjectHash string             `json:"subject_hash"`
}

func (q *Queries) LockLoginAttemptUntil(ctx context.Context, arg LockLoginAttemptUntilParams) (LoginAttempt, error) {
	row := q.db.QueryRow(ctx, lockLoginAttemptUntil,
		arg.LockedUntil,
		arg.Endpoint,
		arg.SubjectType,
		arg.SubjectHash,
	)
	var i LoginAttempt
	err := row.Scan(
		&i.ID,
		&i.Endpoint,
		&i.SubjectType,
		&i.SubjectHash,
		&i.AccountID,
		&i.UsernameNormalized,
		&i.Ip,
		&i.FailedCount,
		&i.LockedUntil,
		&i.LastFailedAt,
		&i.LastSuccessAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordLoginFailure = `-- name: RecordLoginFailure :one
INSERT INTO login_attempts (
    id,
    endpoint,
    subject_type,
    subject_hash,
    account_id,
    username_normalized,
    ip,
    failed_count,
    locked_until,
    last_failed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    1,
    CASE
        WHEN 1 >= $8::integer THEN $9
        ELSE NULL
    END,
    $10
)
ON CONFLICT (endpoint, subject_type, subject_hash) DO UPDATE
SET account_id = COALESCE(EXCLUDED.account_id, login_attempts.account_id),
    username_normalized = COALESCE(EXCLUDED.username_normalized, login_attempts.username_normalized),
    ip = COALESCE(EXCLUDED.ip, login_attempts.ip),
    failed_count = login_attempts.failed_count + 1,
    locked_until = CASE
        WHEN login_attempts.failed_count + 1 >= $8::integer THEN $9
        ELSE login_attempts.locked_until
    END,
    last_failed_at = $10
RETURNING id, endpoint, subject_type, subject_hash, account_id, username_normalized, ip, failed_count, locked_until, last_failed_at, last_success_at, created_at, updated_at
`

type RecordLoginFailureParams struct {
	ID                 pgtype.UUID        `json:"id"`
	Endpoint           string             `json:"endpoint"`
	SubjectType        string             `json:"subject_type"`
	SubjectHash        string             `json:"subject_hash"`
	AccountID          pgtype.UUID        `json:"account_id"`
	UsernameNormalized *string            `json:"username_normalized"`
	Ip                 *netip.Addr        `json:"ip"`
	MaxFailures        int32              `json:"max_failures"`
	LockUntil          interface{}        `json:"lock_until"`
	OccurredAt         pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) (LoginAttempt, error) {
	row := q.db.QueryRow(ctx, recordLoginFailure,
		arg.ID,
		arg.Endpoint,
		arg.SubjectType,
		arg.SubjectHash,
		arg.AccountID,
		arg.UsernameNormalized,
		arg.Ip,
		arg.MaxFailures,
		arg.LockUntil,
		arg.OccurredAt,
	)
	var i LoginAttempt
	err := row.Scan(
		&i.ID,
		&i.Endpoint,
		&i.SubjectType,
		&i.SubjectHash,
		&i.AccountID,
		&i.UsernameNormalized,
		&i.Ip,
		&i.FailedCount,
		&i.LockedUntil,
		&i.LastFailedAt,
		&i.LastSuccessAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordLoginSuccess = `-- name: RecordLoginSuccess :one
UPDATE login_attempts
SET failed_count = 0,
    locked_until = NULL,
    last_success_at = $1
WHERE endpoint = $2
  AND subject_type = $3
  AND subject_hash = $4
RETURNING id, endpoint, subject_type, subject_hash, account_id, username_normalized, ip, failed_count, locked_until, last_failed_at, last_success_at, created_at, updated_at
`

type RecordLoginSuccessParams struct {
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Endpoint    string             `json:"endpoint"`
	SubjectType string             `json:"subject_type"`
	SubjectHash string             `json:"subject_hash"`
}

func (q *Queries) RecordLoginSuccess(ctx context.Context, arg RecordLoginSuccessParams) (LoginAttempt, error) {
	row := q.db.QueryRow(ctx, recordLoginSuccess,
		arg.OccurredAt,
		arg.Endpoint,
		arg.SubjectType,
		arg.SubjectHash,
	)
	var i LoginAttempt
	err := row.Scan(
		&i.ID,
		&i.Endpoint,
		&i.SubjectType,
		&i.SubjectHash,
		&i.AccountID,
		&i.UsernameNormalized,
		&i.Ip,
		&i.FailedCount,
		&i.LockedUntil,
		&i.LastFailedAt,
		&i.LastSuccessAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
