// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                 pgtype.UUID        `json:"id"`
	Username           string             `json:"username"`
	UsernameNormalized string             `json:"username_normalized"`
	DisplayName        string             `json:"display_name"`
	Disabled           bool               `json:"disabled"`
	MfaRequired        bool               `json:"mfa_required"`
	LockedUntil        pgtype.Timestamptz `json:"locked_until"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ArchivedSession struct {
	ID          pgtype.UUID        `json:"id"`
	AccountID   pgtype.UUID        `json:"account_id"`
	ClientID    pgtype.UUID        `json:"client_id"`
	TokenID     *string            `json:"token_id"`
	UserAgentID *string            `json:"user_agent_id"`
	Ip          *netip.Addr        `json:"ip"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AuditEvent struct {
	ID             pgtype.UUID        `json:"id"`
	EventType      string             `json:"event_type"`
	AccountID      pgtype.UUID        `json:"account_id"`
	CredentialID   pgtype.UUID        `json:"credential_id"`
	SessionID      pgtype.UUID        `json:"session_id"`
	ClientID       pgtype.UUID        `json:"client_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	RequestID      string             `json:"request_id"`
	Ip             *netip.Addr        `json:"ip"`
	UserAgent      string             `json:"user_agent"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	Attributes     []byte             `json:"attributes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AuthChallenge struct {
	ID             string             `json:"id"`
	Purpose        string             `json:"purpose"`
	AccountID      pgtype.UUID        `json:"account_id"`
	CredentialID   pgtype.UUID        `json:"credential_id"`
	Provider       *string            `json:"provider"`
	SessionBinding string             `json:"session_binding"`
	RequestID      string             `json:"request_id"`
	Payload        []byte             `json:"payload"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt     pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AuthorizationCode struct {
	ID                  pgtype.UUID        `json:"id"`
	CodeHash            []byte             `json:"code_hash"`
	ClientID            pgtype.UUID        `json:"client_id"`
	AccountID           pgtype.UUID        `json:"account_id"`
	OrganizationID      pgtype.UUID        `json:"organization_id"`
	RedirectUri         string             `json:"redirect_uri"`
	Scopes              []string           `json:"scopes"`
	Nonce               *string            `json:"nonce"`
	CodeChallenge       *string            `json:"code_challenge"`
	CodeChallengeMethod *string            `json:"code_challenge_method"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt          pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type ConsentGrant struct {
	ID             pgtype.UUID        `json:"id"`
	ClientID       pgtype.UUID        `json:"client_id"`
	AccountID      pgtype.UUID        `json:"account_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Scopes         []string           `json:"scopes"`
	GrantedAt      pgtype.Timestamptz `json:"granted_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Credential struct {
	ID              pgtype.UUID        `json:"id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	Kind            string             `json:"kind"`
	Provider        *string            `json:"provider"`
	ExternalSubject *string            `json:"external_subject"`
	DisplayName     string             `json:"display_name"`
	Verified        bool               `json:"verified"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
}

type CredentialPayload struct {
	CredentialID pgtype.UUID        `json:"credential_id"`
	Algorithm    string             `json:"algorithm"`
	KeyRef       string             `json:"key_ref"`
	Nonce        []byte             `json:"nonce"`
	Ciphertext   []byte             `json:"ciphertext"`
	Aad          []byte             `json:"aad"`
	Version      int32              `json:"version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Email struct {
	ID                pgtype.UUID        `json:"id"`
	AccountID         pgtype.UUID        `json:"account_id"`
	Address           string             `json:"address"`
	AddressNormalized string             `json:"address_normalized"`
	Verified          bool               `json:"verified"`
	IsPrimary         bool               `json:"is_primary"`
	VerifiedAt        pgtype.Timestamptz `json:"verified_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Invitation struct {
	ID              pgtype.UUID        `json:"id"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	EmailNormalized string             `json:"email_normalized"`
	Role            string             `json:"role"`
	TokenHash       []byte             `json:"token_hash"`
	InvitedBy       pgtype.UUID        `json:"invited_by"`
	AcceptedBy      pgtype.UUID        `json:"accepted_by"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt      pgtype.Timestamptz `json:"accepted_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type LoginAttempt struct {
	ID                 pgtype.UUID        `json:"id"`
	Endpoint           string             `json:"endpoint"`
	SubjectType        string             `json:"subject_type"`
	SubjectHash        string             `json:"subject_hash"`
	AccountID          pgtype.UUID        `json:"account_id"`
	UsernameNormalized *string            `json:"username_normalized"`
	Ip                 *netip.Addr        `json:"ip"`
	FailedCount        int32              `json:"failed_count"`
	LockedUntil        pgtype.Timestamptz `json:"locked_until"`
	LastFailedAt       pgtype.Timestamptz `json:"last_failed_at"`
	LastSuccessAt      pgtype.Timestamptz `json:"last_success_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Membership struct {
	AccountID      pgtype.UUID        `json:"account_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Role           string             `json:"role"`
	InvitedBy      pgtype.UUID        `json:"invited_by"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type OauthClient struct {
	ID               pgtype.UUID        `json:"id"`
	OrganizationID   pgtype.UUID        `json:"organization_id"`
	OwnerAccountID   pgtype.UUID        `json:"owner_account_id"`
	ClientSecretHash []byte             `json:"client_secret_hash"`
	Name             string             `json:"name"`
	RedirectUris     []string           `json:"redirect_uris"`
	GrantTypes       []string           `json:"grant_types"`
	ResponseTypes    []string           `json:"response_types"`
	Scopes           []string           `json:"scopes"`
	Confidential     bool               `json:"confidential"`
	PkceRequired     bool               `json:"pkce_required"`
	Active           bool               `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type OauthRefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	TokenHash []byte             `json:"token_hash"`
	SessionID pgtype.UUID        `json:"session_id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	ClientID  pgtype.UUID        `json:"client_id"`
	AccountID pgtype.UUID        `json:"account_id"`
	Scopes    []string           `json:"scopes"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RotatedAt pgtype.Timestamptz `json:"rotated_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OidcPendingState struct {
	ID                     string             `json:"id"`
	Provider               string             `json:"provider"`
	SessionBinding         string             `json:"session_binding"`
	StateHash              []byte             `json:"state_hash"`
	NonceHash              []byte             `json:"nonce_hash"`
	PkceVerifierCiphertext []byte             `json:"pkce_verifier_ciphertext"`
	RedirectUri            string             `json:"redirect_uri"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt             pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type OidcProviderLink struct {
	ID              pgtype.UUID        `json:"id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	CredentialID    pgtype.UUID        `json:"credential_id"`
	Provider        string             `json:"provider"`
	ExternalSubject string             `json:"external_subject"`
	Email           *string            `json:"email"`
	EmailVerified   bool               `json:"email_verified"`
	DisplayName     string             `json:"display_name"`
	Claims          []byte             `json:"claims"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Organization struct {
	ID             pgtype.UUID        `json:"id"`
	Slug           string             `json:"slug"`
	SlugNormalized string             `json:"slug_normalized"`
	Name           string             `json:"name"`
	MfaRequired    bool               `json:"mfa_required"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PasswordResetToken struct {
	ID            pgtype.UUID        `json:"id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	TokenHash     []byte             `json:"token_hash"`
	RequestedByIp *netip.Addr        `json:"requested_by_ip"`
	UserAgent     string             `json:"user_agent"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	UsedAt        pgtype.Timestamptz `json:"used_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type RecoveryCode struct {
	ID           pgtype.UUID        `json:"id"`
	AccountID    pgtype.UUID        `json:"account_id"`
	CredentialID pgtype.UUID        `json:"credential_id"`
	CodeHash     []byte             `json:"code_hash"`
	UsedAt       pgtype.Timestamptz `json:"used_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID                pgtype.UUID        `json:"id"`
	SessionID         pgtype.UUID        `json:"session_id"`
	ParentID          pgtype.UUID        `json:"parent_id"`
	ClientID          pgtype.UUID        `json:"client_id"`
	TokenHash         []byte             `json:"token_hash"`
	Scopes            []string           `json:"scopes"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
	RotatedAt         pgtype.Timestamptz `json:"rotated_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID          pgtype.UUID        `json:"id"`
	AccountID   pgtype.UUID        `json:"account_id"`
	ClientID    pgtype.UUID        `json:"client_id"`
	Kind        string             `json:"kind"`
	Status      string             `json:"status"`
	TokenID     *string            `json:"token_id"`
	UserAgentID *string            `json:"user_agent_id"`
	Ip          *netip.Addr        `json:"ip"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SessionFactor struct {
	SessionID        pgtype.UUID        `json:"session_id"`
	FactorKind       string             `json:"factor_kind"`
	ChallengeBinding string             `json:"challenge_binding"`
	VerifiedAt       pgtype.Timestamptz `json:"verified_at"`
	Metadata         []byte             `json:"metadata"`
}

type SessionUserAgent struct {
	FingerprintID string             `json:"fingerprint_id"`
	Ip            *netip.Addr        `json:"ip"`
	Description   string             `json:"description"`
	Headers       []byte             `json:"headers"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type WebauthnCredential struct {
	CredentialID    pgtype.UUID        `json:"credential_id"`
	KeyID           []byte             `json:"key_id"`
	PublicKey       []byte             `json:"public_key"`
	SignCount       int32              `json:"sign_count"`
	RelyingPartyID  string             `json:"relying_party_id"`
	Aaguid          []byte             `json:"aaguid"`
	AttestationType string             `json:"attestation_type"`
	UserVerified    bool               `json:"user_verified"`
	BackedUp        bool               `json:"backed_up"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
