// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset_tokens.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (
    id,
    account_id,
    token_hash,
    requested_by_ip,
    user_agent,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, account_id, token_hash, requested_by_ip, user_agent, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	ID            pgtype.UUID        `json:"id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	TokenHash     []byte             `json:"token_hash"`
	RequestedByIp *netip.Addr        `json:"requested_by_ip"`
	UserAgent     string             `json:"user_agent"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken,
		arg.ID,
		arg.AccountID,
		arg.TokenHash,
		arg.RequestedByIp,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.RequestedByIp,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordResetTargetByEmail = `-- name: GetPasswordResetTargetByEmail :one
SELECT
    a.id,
    a.username,
    a.username_normalized,
    e.address AS email_address,
    e.address_normalized AS email_normalized
FROM emails AS e
JOIN accounts AS a ON a.id = e.account_id
WHERE e.address_normalized = $1
ORDER BY e.is_primary DESC, e.created_at ASC
LIMIT 1
`

type GetPasswordResetTargetByEmailRow struct {
	ID                 pgtype.UUID `json:"id"`
	Username           string      `json:"username"`
	UsernameNormalized string      `json:"username_normalized"`
	EmailAddress       string      `json:"email_address"`
	EmailNormalized    string      `json:"email_normalized"`
}

func (q *Queries) GetPasswordResetTargetByEmail(ctx context.Context, emailNormalized string) (GetPasswordResetTargetByEmailRow, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTargetByEmail, emailNormalized)
	var i GetPasswordResetTargetByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameNormalized,
		&i.EmailAddress,
		&i.EmailNormalized,
	)
	return i, err
}

const getPasswordResetTargetByUsername = `-- name: GetPasswordResetTargetByUsername :one
SELECT
    a.id,
    a.username,
    a.username_normalized,
    e.address AS email_address,
    e.address_normalized AS email_normalized
FROM accounts AS a
JOIN emails AS e ON e.account_id = a.id
WHERE a.username_normalized = $1
  AND e.is_primary = true
ORDER BY e.created_at ASC
LIMIT 1
`

type GetPasswordResetTargetByUsernameRow struct {
	ID                 pgtype.UUID `json:"id"`
	Username           string      `json:"username"`
	UsernameNormalized string      `json:"username_normalized"`
	EmailAddress       string      `json:"email_address"`
	EmailNormalized    string      `json:"email_normalized"`
}

func (q *Queries) GetPasswordResetTargetByUsername(ctx context.Context, usernameNormalized string) (GetPasswordResetTargetByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTargetByUsername, usernameNormalized)
	var i GetPasswordResetTargetByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameNormalized,
		&i.EmailAddress,
		&i.EmailNormalized,
	)
	return i, err
}
