// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) (AuditEvent, error)
	ClearExpiredLoginAttemptLocks(ctx context.Context, expiredAt pgtype.Timestamptz) (int64, error)
	ConsumeAuthChallenge(ctx context.Context, arg ConsumeAuthChallengeParams) (AuthChallenge, error)
	ConsumeOIDCPendingState(ctx context.Context, arg ConsumeOIDCPendingStateParams) (OidcPendingState, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateAuthChallenge(ctx context.Context, arg CreateAuthChallengeParams) (AuthChallenge, error)
	CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error)
	CreateEmail(ctx context.Context, arg CreateEmailParams) (Email, error)
	CreateOIDCPendingState(ctx context.Context, arg CreateOIDCPendingStateParams) (OidcPendingState, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSessionFactor(ctx context.Context, arg CreateSessionFactorParams) (SessionFactor, error)
	DeleteAuthChallenge(ctx context.Context, id string) (int64, error)
	DeleteExpiredAuthChallenges(ctx context.Context, expiredAt pgtype.Timestamptz) (int64, error)
	DeleteExpiredOIDCPendingStates(ctx context.Context, expiredAt pgtype.Timestamptz) (int64, error)
	GetAccountByEmail(ctx context.Context, addressNormalized string) (Account, error)
	GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error)
	GetAccountByUsername(ctx context.Context, usernameNormalized string) (Account, error)
	GetAuthChallenge(ctx context.Context, id string) (AuthChallenge, error)
	GetCredentialByAccountKindProvider(ctx context.Context, arg GetCredentialByAccountKindProviderParams) (Credential, error)
	GetCredentialByID(ctx context.Context, id pgtype.UUID) (Credential, error)
	GetCredentialByIDForAccount(ctx context.Context, arg GetCredentialByIDForAccountParams) (Credential, error)
	GetCredentialByProviderSubject(ctx context.Context, arg GetCredentialByProviderSubjectParams) (Credential, error)
	GetCredentialPayload(ctx context.Context, credentialID pgtype.UUID) (CredentialPayload, error)
	GetLoginAttempt(ctx context.Context, arg GetLoginAttemptParams) (LoginAttempt, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error)
	ListActiveSessionsByAccount(ctx context.Context, arg ListActiveSessionsByAccountParams) ([]Session, error)
	ListCredentialsByAccount(ctx context.Context, accountID pgtype.UUID) ([]Credential, error)
	ListCredentialsByAccountAndKind(ctx context.Context, arg ListCredentialsByAccountAndKindParams) ([]Credential, error)
	ListEmailsByAccount(ctx context.Context, accountID pgtype.UUID) ([]Email, error)
	ListExpiredAuthChallenges(ctx context.Context, arg ListExpiredAuthChallengesParams) ([]AuthChallenge, error)
	ListRecentLoginAuditEvents(ctx context.Context, arg ListRecentLoginAuditEventsParams) ([]AuditEvent, error)
	ListSessionFactors(ctx context.Context, sessionID pgtype.UUID) ([]SessionFactor, error)
	ListSessionsByAccount(ctx context.Context, arg ListSessionsByAccountParams) ([]Session, error)
	LockLoginAttemptUntil(ctx context.Context, arg LockLoginAttemptUntilParams) (LoginAttempt, error)
	RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) (LoginAttempt, error)
	RecordLoginSuccess(ctx context.Context, arg RecordLoginSuccessParams) (LoginAttempt, error)
	RevokeCredential(ctx context.Context, arg RevokeCredentialParams) (Credential, error)
	RevokeCredentialForAccount(ctx context.Context, arg RevokeCredentialForAccountParams) (Credential, error)
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) (RefreshToken, error)
	RevokeRefreshTokenChain(ctx context.Context, arg RevokeRefreshTokenChainParams) ([]RefreshToken, error)
	RevokeSession(ctx context.Context, arg RevokeSessionParams) (Session, error)
	RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (RefreshToken, error)
	UpdateAccountLockout(ctx context.Context, arg UpdateAccountLockoutParams) (Account, error)
	UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) (Account, error)
	UpdateCredentialLastUsed(ctx context.Context, arg UpdateCredentialLastUsedParams) (Credential, error)
	UpdateCredentialState(ctx context.Context, arg UpdateCredentialStateParams) (Credential, error)
	UpdateCredentialStateForAccount(ctx context.Context, arg UpdateCredentialStateForAccountParams) (Credential, error)
	UpsertCredentialPayload(ctx context.Context, arg UpsertCredentialPayloadParams) (CredentialPayload, error)
	UpsertSessionUserAgent(ctx context.Context, arg UpsertSessionUserAgentParams) (SessionUserAgent, error)
}

var _ Querier = (*Queries)(nil)
