// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery_codes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeRecoveryCode = `-- name: ConsumeRecoveryCode :one
UPDATE recovery_codes
SET used_at = $1
WHERE id = $2
  AND account_id = $3
  AND credential_id = $4
  AND used_at IS NULL
RETURNING id, account_id, credential_id, code_hash, used_at, created_at
`

type ConsumeRecoveryCodeParams struct {
	UsedAt       pgtype.Timestamptz `json:"used_at"`
	ID           pgtype.UUID        `json:"id"`
	AccountID    pgtype.UUID        `json:"account_id"`
	CredentialID pgtype.UUID        `json:"credential_id"`
}

func (q *Queries) ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (RecoveryCode, error) {
	row := q.db.QueryRow(ctx, consumeRecoveryCode,
		arg.UsedAt,
		arg.ID,
		arg.AccountID,
		arg.CredentialID,
	)
	var i RecoveryCode
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CredentialID,
		&i.CodeHash,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRecoveryCode = `-- name: CreateRecoveryCode :one
INSERT INTO recovery_codes (
    id,
    account_id,
    credential_id,
    code_hash
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, account_id, credential_id, code_hash, used_at, created_at
`

type CreateRecoveryCodeParams struct {
	ID           pgtype.UUID `json:"id"`
	AccountID    pgtype.UUID `json:"account_id"`
	CredentialID pgtype.UUID `json:"credential_id"`
	CodeHash     []byte      `json:"code_hash"`
}

func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) (RecoveryCode, error) {
	row := q.db.QueryRow(ctx, createRecoveryCode,
		arg.ID,
		arg.AccountID,
		arg.CredentialID,
		arg.CodeHash,
	)
	var i RecoveryCode
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CredentialID,
		&i.CodeHash,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUnusedRecoveryCodes = `-- name: DeleteUnusedRecoveryCodes :execrows
DELETE FROM recovery_codes
WHERE account_id = $1
  AND credential_id = $2
  AND used_at IS NULL
`

type DeleteUnusedRecoveryCodesParams struct {
	AccountID    pgtype.UUID `json:"account_id"`
	CredentialID pgtype.UUID `json:"credential_id"`
}

func (q *Queries) DeleteUnusedRecoveryCodes(ctx context.Context, arg DeleteUnusedRecoveryCodesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUnusedRecoveryCodes, arg.AccountID, arg.CredentialID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listUnusedRecoveryCodes = `-- name: ListUnusedRecoveryCodes :many
SELECT id, account_id, credential_id, code_hash, used_at, created_at
FROM recovery_codes
WHERE account_id = $1
  AND credential_id = $2
  AND used_at IS NULL
ORDER BY created_at ASC
`

type ListUnusedRecoveryCodesParams struct {
	AccountID    pgtype.UUID `json:"account_id"`
	CredentialID pgtype.UUID `json:"credential_id"`
}

func (q *Queries) ListUnusedRecoveryCodes(ctx context.Context, arg ListUnusedRecoveryCodesParams) ([]RecoveryCode, error) {
	rows, err := q.db.Query(ctx, listUnusedRecoveryCodes, arg.AccountID, arg.CredentialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecoveryCode{}
	for rows.Next() {
		var i RecoveryCode
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CredentialID,
			&i.CodeHash,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
