// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    id,
    session_id,
    parent_id,
    client_id,
    token_hash,
    scopes,
    expires_at,
    absolute_expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, session_id, parent_id, client_id, token_hash, scopes, expires_at, absolute_expires_at, rotated_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	ID                pgtype.UUID        `json:"id"`
	SessionID         pgtype.UUID        `json:"session_id"`
	ParentID          pgtype.UUID        `json:"parent_id"`
	ClientID          pgtype.UUID        `json:"client_id"`
	TokenHash         []byte             `json:"token_hash"`
	Scopes            []string           `json:"scopes"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.ID,
		arg.SessionID,
		arg.ParentID,
		arg.ClientID,
		arg.TokenHash,
		arg.Scopes,
		arg.ExpiresAt,
		arg.AbsoluteExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ParentID,
		&i.ClientID,
		&i.TokenHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    account_id,
    client_id,
    kind,
    status,
    token_id,
    user_agent_id,
    ip,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, account_id, client_id, kind, status, token_id, user_agent_id, ip, expires_at, revoked_at, created_at, updated_at
`

type CreateSessionParams struct {
	ID          pgtype.UUID        `json:"id"`
	AccountID   pgtype.UUID        `json:"account_id"`
	ClientID    pgtype.UUID        `json:"client_id"`
	Kind        string             `json:"kind"`
	Status      string             `json:"status"`
	TokenID     *string            `json:"token_id"`
	UserAgentID *string            `json:"user_agent_id"`
	Ip          *netip.Addr        `json:"ip"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.AccountID,
		arg.ClientID,
		arg.Kind,
		arg.Status,
		arg.TokenID,
		arg.UserAgentID,
		arg.Ip,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ClientID,
		&i.Kind,
		&i.Status,
		&i.TokenID,
		&i.UserAgentID,
		&i.Ip,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSessionFactor = `-- name: CreateSessionFactor :one
INSERT INTO session_factors (
    session_id,
    factor_kind,
    challenge_binding,
    verified_at,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (session_id, factor_kind) DO UPDATE
SET challenge_binding = EXCLUDED.challenge_binding,
    verified_at = EXCLUDED.verified_at,
    metadata = EXCLUDED.metadata
RETURNING session_id, factor_kind, challenge_binding, verified_at, metadata
`

type CreateSessionFactorParams struct {
	SessionID        pgtype.UUID        `json:"session_id"`
	FactorKind       string             `json:"factor_kind"`
	ChallengeBinding string             `json:"challenge_binding"`
	VerifiedAt       pgtype.Timestamptz `json:"verified_at"`
	Metadata         []byte             `json:"metadata"`
}

func (q *Queries) CreateSessionFactor(ctx context.Context, arg CreateSessionFactorParams) (SessionFactor, error) {
	row := q.db.QueryRow(ctx, createSessionFactor,
		arg.SessionID,
		arg.FactorKind,
		arg.ChallengeBinding,
		arg.VerifiedAt,
		arg.Metadata,
	)
	var i SessionFactor
	err := row.Scan(
		&i.SessionID,
		&i.FactorKind,
		&i.ChallengeBinding,
		&i.VerifiedAt,
		&i.Metadata,
	)
	return i, err
}

const getActiveSessionByID = `-- name: GetActiveSessionByID :one
SELECT id, account_id, client_id, kind, status, token_id, user_agent_id, ip, expires_at, revoked_at, created_at, updated_at
FROM sessions
WHERE id = $1
  AND kind = 'full'
  AND status = 'active'
  AND expires_at > $2
`

type GetActiveSessionByIDParams struct {
	ID       pgtype.UUID        `json:"id"`
	ActiveAt pgtype.Timestamptz `json:"active_at"`
}

func (q *Queries) GetActiveSessionByID(ctx context.Context, arg GetActiveSessionByIDParams) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByID, arg.ID, arg.ActiveAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ClientID,
		&i.Kind,
		&i.Status,
		&i.TokenID,
		&i.UserAgentID,
		&i.Ip,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, session_id, parent_id, client_id, token_hash, scopes, expires_at, absolute_expires_at, rotated_at, revoked_at, created_at
FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ParentID,
		&i.ClientID,
		&i.TokenHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, account_id, client_id, kind, status, token_id, user_agent_id, ip, expires_at, revoked_at, created_at, updated_at
FROM sessions
WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ClientID,
		&i.Kind,
		&i.Status,
		&i.TokenID,
		&i.UserAgentID,
		&i.Ip,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAccountSessions = `-- name: ListActiveAccountSessions :many
SELECT
    s.id,
    s.account_id,
    s.client_id,
    s.ip,
    COALESCE(ua.description, '')::text AS user_agent,
    s.created_at,
    s.expires_at
FROM sessions AS s
LEFT JOIN session_user_agents AS ua ON ua.fingerprint_id = s.user_agent_id
WHERE s.account_id = $1
  AND s.kind = 'full'
  AND s.status = 'active'
  AND s.expires_at > $2
ORDER BY s.created_at DESC
`

type ListActiveAccountSessionsParams struct {
	AccountID pgtype.UUID        `json:"account_id"`
	ActiveAt  pgtype.Timestamptz `json:"active_at"`
}

type ListActiveAccountSessionsRow struct {
	ID        pgtype.UUID        `json:"id"`
	AccountID pgtype.UUID        `json:"account_id"`
	ClientID  pgtype.UUID        `json:"client_id"`
	Ip        *netip.Addr        `json:"ip"`
	UserAgent string             `json:"user_agent"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ListActiveAccountSessions(ctx context.Context, arg ListActiveAccountSessionsParams) ([]ListActiveAccountSessionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveAccountSessions, arg.AccountID, arg.ActiveAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAccountSessionsRow{}
	for rows.Next() {
		var i ListActiveAccountSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ClientID,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSessionsByAccount = `-- name: ListActiveSessionsByAccount :many
SELECT id, account_id, client_id, kind, status, token_id, user_agent_id, ip, expires_at, revoked_at, created_at, updated_at
FROM sessions
WHERE account_id = $1
  AND status = 'active'
  AND expires_at > $2
ORDER BY created_at DESC
`

type ListActiveSessionsByAccountParams struct {
	AccountID pgtype.UUID        `json:"account_id"`
	ActiveAt  pgtype.Timestamptz `json:"active_at"`
}

func (q *Queries) ListActiveSessionsByAccount(ctx context.Context, arg ListActiveSessionsByAccountParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listActiveSessionsByAccount, arg.AccountID, arg.ActiveAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ClientID,
			&i.Kind,
			&i.Status,
			&i.TokenID,
			&i.UserAgentID,
			&i.Ip,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionFactors = `-- name: ListSessionFactors :many
SELECT session_id, factor_kind, challenge_binding, verified_at, metadata
FROM session_factors
WHERE session_id = $1
ORDER BY verified_at ASC
`

func (q *Queries) ListSessionFactors(ctx context.Context, sessionID pgtype.UUID) ([]SessionFactor, error) {
	rows, err := q.db.Query(ctx, listSessionFactors, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionFactor{}
	for rows.Next() {
		var i SessionFactor
		if err := rows.Scan(
			&i.SessionID,
			&i.FactorKind,
			&i.ChallengeBinding,
			&i.VerifiedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByAccount = `-- name: ListSessionsByAccount :many
SELECT id, account_id, client_id, kind, status, token_id, user_agent_id, ip, expires_at, revoked_at, created_at, updated_at
FROM sessions
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListSessionsByAccountParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	RowLimit  int32       `json:"row_limit"`
}

func (q *Queries) ListSessionsByAccount(ctx context.Context, arg ListSessionsByAccountParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByAccount, arg.AccountID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ClientID,
			&i.Kind,
			&i.Status,
			&i.TokenID,
			&i.UserAgentID,
			&i.Ip,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :one
UPDATE refresh_tokens
SET revoked_at = $1
WHERE id = $2
  AND revoked_at IS NULL
RETURNING id, session_id, parent_id, client_id, token_hash, scopes, expires_at, absolute_expires_at, rotated_at, revoked_at, created_at
`

type RevokeRefreshTokenParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, revokeRefreshToken, arg.RevokedAt, arg.ID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ParentID,
		&i.ClientID,
		&i.TokenHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshTokenChain = `-- name: RevokeRefreshTokenChain :many
WITH RECURSIVE token_ancestors AS (
    SELECT refresh_tokens.id, refresh_tokens.parent_id
    FROM refresh_tokens
    WHERE refresh_tokens.id = $2

    UNION ALL

    SELECT rt.id, rt.parent_id
    FROM refresh_tokens AS rt
    JOIN token_ancestors AS ta ON ta.parent_id = rt.id
),
token_chain AS (
    SELECT id
    FROM token_ancestors

    UNION ALL

    SELECT rt.id
    FROM refresh_tokens AS rt
    JOIN token_chain AS tc ON rt.parent_id = tc.id
)
UPDATE refresh_tokens
SET revoked_at = $1
WHERE id IN (SELECT id FROM token_chain)
  AND revoked_at IS NULL
RETURNING id, session_id, parent_id, client_id, token_hash, scopes, expires_at, absolute_expires_at, rotated_at, revoked_at, created_at
`

type RevokeRefreshTokenChainParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	RootID    pgtype.UUID        `json:"root_id"`
}

func (q *Queries) RevokeRefreshTokenChain(ctx context.Context, arg RevokeRefreshTokenChainParams) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, revokeRefreshTokenChain, arg.RevokedAt, arg.RootID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefreshToken{}
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ParentID,
			&i.ClientID,
			&i.TokenHash,
			&i.Scopes,
			&i.ExpiresAt,
			&i.AbsoluteExpiresAt,
			&i.RotatedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshTokensByAccount = `-- name: RevokeRefreshTokensByAccount :many
UPDATE refresh_tokens
SET revoked_at = $1
WHERE session_id IN (
    SELECT id
    FROM sessions
    WHERE account_id = $2
)
  AND revoked_at IS NULL
RETURNING id, session_id, parent_id, client_id, token_hash, scopes, expires_at, absolute_expires_at, rotated_at, revoked_at, created_at
`

type RevokeRefreshTokensByAccountParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	AccountID pgtype.UUID        `json:"account_id"`
}

func (q *Queries) RevokeRefreshTokensByAccount(ctx context.Context, arg RevokeRefreshTokensByAccountParams) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, revokeRefreshTokensByAccount, arg.RevokedAt, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefreshToken{}
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ParentID,
			&i.ClientID,
			&i.TokenHash,
			&i.Scopes,
			&i.ExpiresAt,
			&i.AbsoluteExpiresAt,
			&i.RotatedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshTokensBySession = `-- name: RevokeRefreshTokensBySession :many
UPDATE refresh_tokens
SET revoked_at = $1
WHERE session_id = $2
  AND revoked_at IS NULL
RETURNING id, session_id, parent_id, client_id, token_hash, scopes, expires_at, absolute_expires_at, rotated_at, revoked_at, created_at
`

type RevokeRefreshTokensBySessionParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	SessionID pgtype.UUID        `json:"session_id"`
}

func (q *Queries) RevokeRefreshTokensBySession(ctx context.Context, arg RevokeRefreshTokensBySessionParams) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, revokeRefreshTokensBySession, arg.RevokedAt, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefreshToken{}
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ParentID,
			&i.ClientID,
			&i.TokenHash,
			&i.Scopes,
			&i.ExpiresAt,
			&i.AbsoluteExpiresAt,
			&i.RotatedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :one
UPDATE sessions
SET status = 'revoked',
    revoked_at = $1
WHERE id = $2
  AND status = 'active'
RETURNING id, account_id, client_id, kind, status, token_id, user_agent_id, ip, expires_at, revoked_at, created_at, updated_at
`

type RevokeSessionParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, revokeSession, arg.RevokedAt, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ClientID,
		&i.Kind,
		&i.Status,
		&i.TokenID,
		&i.UserAgentID,
		&i.Ip,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeSessionForAccount = `-- name: RevokeSessionForAccount :one
UPDATE sessions
SET status = 'revoked',
    revoked_at = $1
WHERE id = $2
  AND account_id = $3
  AND status = 'active'
RETURNING id, account_id, client_id, kind, status, token_id, user_agent_id, ip, expires_at, revoked_at, created_at, updated_at
`

type RevokeSessionForAccountParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	ID        pgtype.UUID        `json:"id"`
	AccountID pgtype.UUID        `json:"account_id"`
}

func (q *Queries) RevokeSessionForAccount(ctx context.Context, arg RevokeSessionForAccountParams) (Session, error) {
	row := q.db.QueryRow(ctx, revokeSessionForAccount, arg.RevokedAt, arg.ID, arg.AccountID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ClientID,
		&i.Kind,
		&i.Status,
		&i.TokenID,
		&i.UserAgentID,
		&i.Ip,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeSessionsByAccount = `-- name: RevokeSessionsByAccount :many
UPDATE sessions
SET status = 'revoked',
    revoked_at = $1
WHERE account_id = $2
  AND kind = 'full'
  AND status = 'active'
RETURNING id, account_id, client_id, kind, status, token_id, user_agent_id, ip, expires_at, revoked_at, created_at, updated_at
`

type RevokeSessionsByAccountParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	AccountID pgtype.UUID        `json:"account_id"`
}

func (q *Queries) RevokeSessionsByAccount(ctx context.Context, arg RevokeSessionsByAccountParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, revokeSessionsByAccount, arg.RevokedAt, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ClientID,
			&i.Kind,
			&i.Status,
			&i.TokenID,
			&i.UserAgentID,
			&i.Ip,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateRefreshToken = `-- name: RotateRefreshToken :one
UPDATE refresh_tokens
SET rotated_at = $1
WHERE id = $2
  AND rotated_at IS NULL
  AND revoked_at IS NULL
RETURNING id, session_id, parent_id, client_id, token_hash, scopes, expires_at, absolute_expires_at, rotated_at, revoked_at, created_at
`

type RotateRefreshTokenParams struct {
	RotatedAt pgtype.Timestamptz `json:"rotated_at"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, rotateRefreshToken, arg.RotatedAt, arg.ID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ParentID,
		&i.ClientID,
		&i.TokenHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateSessionAccessToken = `-- name: UpdateSessionAccessToken :one
UPDATE sessions
SET token_id = $1
WHERE id = $2
  AND kind = 'full'
  AND status = 'active'
RETURNING id, account_id, client_id, kind, status, token_id, user_agent_id, ip, expires_at, revoked_at, created_at, updated_at
`

type UpdateSessionAccessTokenParams struct {
	TokenID *string     `json:"token_id"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSessionAccessToken(ctx context.Context, arg UpdateSessionAccessTokenParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionAccessToken, arg.TokenID, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ClientID,
		&i.Kind,
		&i.Status,
		&i.TokenID,
		&i.UserAgentID,
		&i.Ip,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSessionUserAgent = `-- name: UpsertSessionUserAgent :one
INSERT INTO session_user_agents (
    fingerprint_id,
    ip,
    description,
    headers
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (fingerprint_id) DO UPDATE
SET ip = EXCLUDED.ip,
    description = EXCLUDED.description,
    headers = EXCLUDED.headers
RETURNING fingerprint_id, ip, description, headers, created_at, updated_at
`

type UpsertSessionUserAgentParams struct {
	FingerprintID string      `json:"fingerprint_id"`
	Ip            *netip.Addr `json:"ip"`
	Description   string      `json:"description"`
	Headers       []byte      `json:"headers"`
}

func (q *Queries) UpsertSessionUserAgent(ctx context.Context, arg UpsertSessionUserAgentParams) (SessionUserAgent, error) {
	row := q.db.QueryRow(ctx, upsertSessionUserAgent,
		arg.FingerprintID,
		arg.Ip,
		arg.Description,
		arg.Headers,
	)
	var i SessionUserAgent
	err := row.Scan(
		&i.FingerprintID,
		&i.Ip,
		&i.Description,
		&i.Headers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
