// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webauthn_credentials.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebAuthnCredential = `-- name: CreateWebAuthnCredential :one
INSERT INTO webauthn_credentials (
    credential_id,
    key_id,
    public_key,
    sign_count,
    relying_party_id,
    aaguid,
    attestation_type,
    user_verified,
    backed_up,
    transports,
    backup_eligible,
    authenticator_attachment
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING credential_id, key_id, public_key, sign_count, relying_party_id, aaguid, attestation_type, user_verified, backed_up, created_at, updated_at, transports, backup_eligible, authenticator_attachment
`

type CreateWebAuthnCredentialParams struct {
	CredentialID            pgtype.UUID `json:"credential_id"`
	KeyID                   []byte      `json:"key_id"`
	PublicKey               []byte      `json:"public_key"`
	SignCount               int32       `json:"sign_count"`
	RelyingPartyID          string      `json:"relying_party_id"`
	Aaguid                  []byte      `json:"aaguid"`
	AttestationType         string      `json:"attestation_type"`
	UserVerified            bool        `json:"user_verified"`
	BackedUp                bool        `json:"backed_up"`
	Transports              []string    `json:"transports"`
	BackupEligible          bool        `json:"backup_eligible"`
	AuthenticatorAttachment string      `json:"authenticator_attachment"`
}

func (q *Queries) CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, createWebAuthnCredential,
		arg.CredentialID,
		arg.KeyID,
		arg.PublicKey,
		arg.SignCount,
		arg.RelyingPartyID,
		arg.Aaguid,
		arg.AttestationType,
		arg.UserVerified,
		arg.BackedUp,
		arg.Transports,
		arg.BackupEligible,
		arg.AuthenticatorAttachment,
	)
	var i WebauthnCredential
	err := row.Scan(
		&i.CredentialID,
		&i.KeyID,
		&i.PublicKey,
		&i.SignCount,
		&i.RelyingPartyID,
		&i.Aaguid,
		&i.AttestationType,
		&i.UserVerified,
		&i.BackedUp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Transports,
		&i.BackupEligible,
		&i.AuthenticatorAttachment,
	)
	return i, err
}

const getWebAuthnCredentialByCredentialID = `-- name: GetWebAuthnCredentialByCredentialID :one
SELECT c.id, c.account_id, c.kind, c.provider, c.external_subject, c.display_name, c.verified, c.created_at, c.updated_at, c.last_used_at, c.revoked_at, wc.credential_id, wc.key_id, wc.public_key, wc.sign_count, wc.relying_party_id, wc.aaguid, wc.attestation_type, wc.user_verified, wc.backed_up, wc.created_at, wc.updated_at, wc.transports, wc.backup_eligible, wc.authenticator_attachment
FROM credentials AS c
JOIN webauthn_credentials AS wc ON wc.credential_id = c.id
WHERE c.id = $1
  AND c.kind = 'webauthn'
  AND c.revoked_at IS NULL
`

type GetWebAuthnCredentialByCredentialIDRow struct {
	Credential         Credential         `json:"credential"`
	WebauthnCredential WebauthnCredential `json:"webauthn_credential"`
}

func (q *Queries) GetWebAuthnCredentialByCredentialID(ctx context.Context, credentialID pgtype.UUID) (GetWebAuthnCredentialByCredentialIDRow, error) {
	row := q.db.QueryRow(ctx, getWebAuthnCredentialByCredentialID, credentialID)
	var i GetWebAuthnCredentialByCredentialIDRow
	err := row.Scan(
		&i.Credential.ID,
		&i.Credential.AccountID,
		&i.Credential.Kind,
		&i.Credential.Provider,
		&i.Credential.ExternalSubject,
		&i.Credential.DisplayName,
		&i.Credential.Verified,
		&i.Credential.CreatedAt,
		&i.Credential.UpdatedAt,
		&i.Credential.LastUsedAt,
		&i.Credential.RevokedAt,
		&i.WebauthnCredential.CredentialID,
		&i.WebauthnCredential.KeyID,
		&i.WebauthnCredential.PublicKey,
		&i.WebauthnCredential.SignCount,
		&i.WebauthnCredential.RelyingPartyID,
		&i.WebauthnCredential.Aaguid,
		&i.WebauthnCredential.AttestationType,
		&i.WebauthnCredential.UserVerified,
		&i.WebauthnCredential.BackedUp,
		&i.WebauthnCredential.CreatedAt,
		&i.WebauthnCredential.UpdatedAt,
		&i.WebauthnCredential.Transports,
		&i.WebauthnCredential.BackupEligible,
		&i.WebauthnCredential.AuthenticatorAttachment,
	)
	return i, err
}

const getWebAuthnCredentialByKeyID = `-- name: GetWebAuthnCredentialByKeyID :one
SELECT c.id, c.account_id, c.kind, c.provider, c.external_subject, c.display_name, c.verified, c.created_at, c.updated_at, c.last_used_at, c.revoked_at, wc.credential_id, wc.key_id, wc.public_key, wc.sign_count, wc.relying_party_id, wc.aaguid, wc.attestation_type, wc.user_verified, wc.backed_up, wc.created_at, wc.updated_at, wc.transports, wc.backup_eligible, wc.authenticator_attachment
FROM credentials AS c
JOIN webauthn_credentials AS wc ON wc.credential_id = c.id
WHERE wc.key_id = $1
  AND c.kind = 'webauthn'
  AND c.revoked_at IS NULL
`

type GetWebAuthnCredentialByKeyIDRow struct {
	Credential         Credential         `json:"credential"`
	WebauthnCredential WebauthnCredential `json:"webauthn_credential"`
}

func (q *Queries) GetWebAuthnCredentialByKeyID(ctx context.Context, keyID []byte) (GetWebAuthnCredentialByKeyIDRow, error) {
	row := q.db.QueryRow(ctx, getWebAuthnCredentialByKeyID, keyID)
	var i GetWebAuthnCredentialByKeyIDRow
	err := row.Scan(
		&i.Credential.ID,
		&i.Credential.AccountID,
		&i.Credential.Kind,
		&i.Credential.Provider,
		&i.Credential.ExternalSubject,
		&i.Credential.DisplayName,
		&i.Credential.Verified,
		&i.Credential.CreatedAt,
		&i.Credential.UpdatedAt,
		&i.Credential.LastUsedAt,
		&i.Credential.RevokedAt,
		&i.WebauthnCredential.CredentialID,
		&i.WebauthnCredential.KeyID,
		&i.WebauthnCredential.PublicKey,
		&i.WebauthnCredential.SignCount,
		&i.WebauthnCredential.RelyingPartyID,
		&i.WebauthnCredential.Aaguid,
		&i.WebauthnCredential.AttestationType,
		&i.WebauthnCredential.UserVerified,
		&i.WebauthnCredential.BackedUp,
		&i.WebauthnCredential.CreatedAt,
		&i.WebauthnCredential.UpdatedAt,
		&i.WebauthnCredential.Transports,
		&i.WebauthnCredential.BackupEligible,
		&i.WebauthnCredential.AuthenticatorAttachment,
	)
	return i, err
}

const listWebAuthnCredentialsByAccount = `-- name: ListWebAuthnCredentialsByAccount :many
SELECT c.id, c.account_id, c.kind, c.provider, c.external_subject, c.display_name, c.verified, c.created_at, c.updated_at, c.last_used_at, c.revoked_at, wc.credential_id, wc.key_id, wc.public_key, wc.sign_count, wc.relying_party_id, wc.aaguid, wc.attestation_type, wc.user_verified, wc.backed_up, wc.created_at, wc.updated_at, wc.transports, wc.backup_eligible, wc.authenticator_attachment
FROM credentials AS c
JOIN webauthn_credentials AS wc ON wc.credential_id = c.id
WHERE c.account_id = $1
  AND c.kind = 'webauthn'
  AND c.revoked_at IS NULL
  AND ($2::text = '' OR wc.relying_party_id = $2)
ORDER BY c.created_at ASC
`

type ListWebAuthnCredentialsByAccountParams struct {
	AccountID      pgtype.UUID `json:"account_id"`
	RelyingPartyID string      `json:"relying_party_id"`
}

type ListWebAuthnCredentialsByAccountRow struct {
	Credential         Credential         `json:"credential"`
	WebauthnCredential WebauthnCredential `json:"webauthn_credential"`
}

func (q *Queries) ListWebAuthnCredentialsByAccount(ctx context.Context, arg ListWebAuthnCredentialsByAccountParams) ([]ListWebAuthnCredentialsByAccountRow, error) {
	rows, err := q.db.Query(ctx, listWebAuthnCredentialsByAccount, arg.AccountID, arg.RelyingPartyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWebAuthnCredentialsByAccountRow{}
	for rows.Next() {
		var i ListWebAuthnCredentialsByAccountRow
		if err := rows.Scan(
			&i.Credential.ID,
			&i.Credential.AccountID,
			&i.Credential.Kind,
			&i.Credential.Provider,
			&i.Credential.ExternalSubject,
			&i.Credential.DisplayName,
			&i.Credential.Verified,
			&i.Credential.CreatedAt,
			&i.Credential.UpdatedAt,
			&i.Credential.LastUsedAt,
			&i.Credential.RevokedAt,
			&i.WebauthnCredential.CredentialID,
			&i.WebauthnCredential.KeyID,
			&i.WebauthnCredential.PublicKey,
			&i.WebauthnCredential.SignCount,
			&i.WebauthnCredential.RelyingPartyID,
			&i.WebauthnCredential.Aaguid,
			&i.WebauthnCredential.AttestationType,
			&i.WebauthnCredential.UserVerified,
			&i.WebauthnCredential.BackedUp,
			&i.WebauthnCredential.CreatedAt,
			&i.WebauthnCredential.UpdatedAt,
			&i.WebauthnCredential.Transports,
			&i.WebauthnCredential.BackupEligible,
			&i.WebauthnCredential.AuthenticatorAttachment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebAuthnCredentialAssertion = `-- name: UpdateWebAuthnCredentialAssertion :one
UPDATE webauthn_credentials
SET sign_count = $1,
    user_verified = $2,
    backed_up = $3,
    transports = $4,
    backup_eligible = $5,
    authenticator_attachment = $6
WHERE credential_id = $7
RETURNING credential_id, key_id, public_key, sign_count, relying_party_id, aaguid, attestation_type, user_verified, backed_up, created_at, updated_at, transports, backup_eligible, authenticator_attachment
`

type UpdateWebAuthnCredentialAssertionParams struct {
	SignCount               int32       `json:"sign_count"`
	UserVerified            bool        `json:"user_verified"`
	BackedUp                bool        `json:"backed_up"`
	Transports              []string    `json:"transports"`
	BackupEligible          bool        `json:"backup_eligible"`
	AuthenticatorAttachment string      `json:"authenticator_attachment"`
	CredentialID            pgtype.UUID `json:"credential_id"`
}

func (q *Queries) UpdateWebAuthnCredentialAssertion(ctx context.Context, arg UpdateWebAuthnCredentialAssertionParams) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, updateWebAuthnCredentialAssertion,
		arg.SignCount,
		arg.UserVerified,
		arg.BackedUp,
		arg.Transports,
		arg.BackupEligible,
		arg.AuthenticatorAttachment,
		arg.CredentialID,
	)
	var i WebauthnCredential
	err := row.Scan(
		&i.CredentialID,
		&i.KeyID,
		&i.PublicKey,
		&i.SignCount,
		&i.RelyingPartyID,
		&i.Aaguid,
		&i.AttestationType,
		&i.UserVerified,
		&i.BackedUp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Transports,
		&i.BackupEligible,
		&i.AuthenticatorAttachment,
	)
	return i, err
}
